version: "3.7"

networks:
  jarvis:
    external: false

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    hostname: caddy
    networks:
      - jarvis
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - $CONFIG_DIR:/config
      - $DATA_DIR:/data

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    hostname: cadvisor
    networks:
      - jarvis
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: root
    hostname: grafana
    networks:
      - jarvis
    ports:
      - 3000:3000
    depends_on:
      - cadvisor
      - node_exporter
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP
    volumes:
      - $CONFIG_DIR/grafana:/var/lib/grafana
      - $CONFIG_DIR/grafana/provisioning:/etc/grafana/provisioning

  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    hostname: homer
    networks:
      - jarvis
    volumes:
      - $CONFIG_DIR/homer/:/www/assets

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    hostname: jellyfin
    networks:
      - jarvis
    ports:
      - 8096:8096
    volumes:
      - $CONFIG_DIR/jellyfin:/config
      - $DATA_DIR/cache:/cache
      - $DATA_DIR/media:/media

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    hostname: node_exporter
    networks:
      - jarvis
    ports:
      - 9100:9100
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    hostname: ombi
    networks:
      - jarvis
    ports:
      - 3579:3579
    environment:
      - TZ=Europe/London
    volumes:
      - $CONFIG_DIR/ombi:/config

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    hostname: prometheus
    user: root
    networks:
      - jarvis
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - $CONFIG_DIR/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - $CONFIG_DIR/prometheus/:/prometheus

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
      - jarvis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
