version: '3'

networks:
    jarvis:
        external: false

services:
    # Docker Metrics
    cadvisor:
        image: 'google/cadvisor:latest'
        container_name: cadvisor
        restart: always
        networks:
            - jarvis
        ports:
            - '9090:8080'
        volumes:
            - '/:/rootfs:ro'
            - '/var/run:/var/run:rw'
            - '/sys:/sys:ro'
            - '/var/lib/docker/:/var/lib/docker:ro'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:cadvisor.${DOMAIN}'
            - "traefik.protocol=https"

    # Monitoring Dashboard
    grafana:
        image: 'grafana/grafana:latest'
        container_name: grafana
        restart: always
        networks:
            - jarvis
        ports:
            - '3000:3000'
        volumes:
            - '${CONFIG_DIR}/grafana:/var/lib/grafana'
            - '${CONFIG_DIR}/grafana/provisioning/:/etc/grafana/provisioning'
        environment:
            - 'GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel'
        depends_on:
            - cadvisor
            - influxdb
            - varken
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:monitoring.${DOMAIN}'
            - "traefik.protocol=https"

    # Stack Manager
    heimdall:
        image: 'linuxserver/heimdall:latest'
        container_name: heimdall
        restart: always
        networks:
            - jarvis
        ports:
            - '81:80'
            - '444:443'
        environment:
            - 'PUID=${USER_UID}'
            - 'PGID=${USER_GID}'
            - 'TZ=Europe/London'
        volumes:
            - '${CONFIG_DIR}/heimdall:/config'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:${DOMAIN},manager.${DOMAIN}'
            - "traefik.protocol=https"

    # Database For Grafana/Varken
    influxdb:
        image: 'influxdb:latest'
        container_name: influxdb
        restart: always
        networks:
            - jarvis
        ports:
            - '8086:8086'
        environment:
            - INFLUXDB_DB=jarvis
        volumes:
            - '${CONFIG_DIR}/influxdb:/var/lib/influxdb'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:db.${DOMAIN}'
            - "traefik.protocol=https"

    # Content requesting
    ombi:
        image: 'linuxserver/ombi:latest'
        container_name: ombi
        restart: always
        ports:
            - '3579:3579'
        environment:
            - 'PUID=${USER_UID}'
            - 'PGID=${USER_GID}'
            - 'TZ=Europe/London'
        volumes:
            - '${CONFIG_DIR}/ombi:/config'
        depends_on:
            - plex
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:request.${DOMAIN}'
            - "traefik.protocol=https"

    # Content Streaming
    plex:
        image: 'linuxserver/plex:latest'
        container_name: plex
        restart: always
        networks:
            - jarvis
        ports:
            - '32400:32400'
            - '32400:32400/udp'
            - '32469:32469'
            - '32469:32469/udp'
            - '5353:5353/udp'
            - '1900:1900/udp'
        environment:
            - 'VERSION=docker'
            - 'PUID=${USER_UID}'
            - 'PGID=${USER_GID}'
        volumes:
            - '${CONFIG_DIR}/plex:/config'
            - '${TRANSCODE_DIR}:/transcode'
            - '${MEDIA_READ_DIR}/movies:/data/movies'
            - '${MEDIA_READ_DIR}/tvshows:/data/tvshows'
            - '${MEDIA_READ_DIR}/extras:/data/extras'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:plex.${DOMAIN}'
            - "traefik.protocol=https"
            - "traefik.port=32400"

    # Plex Metrics
    tautulli:
        image: 'linuxserver/tautulli:latest'
        container_name: tautulli
        restart: always
        networks:
            - jarvis
        ports:
            - '8181:8181'
        environment:
            - 'PUID=${USER_UID}'
            - 'PGID=${USER_GID}'
            - 'TZ=Europe/London'
        volumes:
            - '${CONFIG_DIR}/tautulli:/config'
            - '${CONFIG_DIR}/plex/Library/Application Support/Plex Media Server/Logs/:/logs'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:tautulli.${DOMAIN}'
            - "traefik.protocol=https"
    
    # Reverse Proxy
    traefik:
        image: 'traefik:latest'
        container_name: traefik
        restart: always
        command: '--api --docker'
        networks:
            - jarvis
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        expose:
            - 8080
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${CONFIG_DIR}/traefik.toml:/traefik.toml'
            - '${CONFIG_DIR}/acme.json:/acme.json'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=jarvis"
            - 'traefik.frontend.rule=Host:proxy.${DOMAIN}'
            - "traefik.protocol=https"
            - 'traefik.port=8080'
    
    # Plex Metrics Aggregator
    varken:
        image: 'boerderij/varken:latest'
        container_name: varken
        restart: always
        volumes:
            - '${CONFIG_DIR}/varken:/config'
        environment:
            - 'PGID=${USER_GID}'
            - 'PUID=${USER_UID}'
            - 'TZ=Europe/London'
        depends_on:
            - influxdb
            - tautulli
