version: '3'
services:
    cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        restart: always
        volumes:
            - '/:/rootfs:ro'
            - '/var/run:/var/run:rw'
            - '/sys:/sys:ro'
            - '/var/lib/docker/:/var/lib/docker:ro'
        ports:
            - '9090:8080'
        labels:
            - 'traefik.frontend.rule=Host:cadvisor.${DOMAIN}'
    grafana:
        image: 'grafana/grafana:latest'
        container_name: grafana
        restart: always
        ports:
            - '3001:3000'
        volumes:
            - '${CONFIG_DIR}/grafana:/var/lib/grafana'
            - '${CONFIG_DIR}/grafana/provisioning/:/etc/grafana/provisioning'
        environment:
            - 'GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel'
        depends_on:
            - influxdb
            - cadvisor
            - varken
        labels:
            - 'traefik.frontend.rule=Host:monitoring.${DOMAIN}'
    heimdall:
        image: 'linuxserver/heimdall:latest'
        container_name: heimdall
        restart: always
        ports:
            - '81:80'
            - '444:443'
        environment:
            - 'PUID=${UID}'
            - 'PGID=${GID}'
            - TZ=Europe/London
        volumes:
            - '${CONFIG_DIR}/heimdall:/config'
        labels:
            - 'traefik.frontend.rule=Host:manager.${DOMAIN}'
    influxdb:
        image: 'influxdb:latest'
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        environment:
            - INFLUXDB_DB=jarvis
        volumes:
            - '${CONFIG_DIR}/influxdb:/var/lib/influxdb'
        labels:
            - 'traefik.frontend.rule=Host:db.${DOMAIN}'
    ombi:
        image: 'linuxserver/ombi:latest'
        container_name: ombi
        restart: always
        ports:
            - '3579:3579'
        environment:
            - 'PUID=${UID}'
            - 'PGID=${GID}'
            - TZ=Europe/London
        volumes:
            - '${CONFIG_DIR}/ombi:/config'
        depends_on:
            - plex
        labels:
            - 'traefik.frontend.rule=Host:request.${DOMAIN}'
    plex:
        image: 'linuxserver/plex:latest'
        container_name: plex
        restart: always
        networks:
            - default
        ports:
            - '32400:32400'
            - '32400:32400/udp'
            - '32469:32469'
            - '32469:32469/udp'
            - '5353:5353/udp'
            - '1900:1900/udp'
        environment:
            - VERSION=docker
            - 'PUID=${UID}'
            - 'PGID=${GID}'
        volumes:
            - '${CONFIG_DIR}/plex:/config'
            - '${TRANSCODE_DIR}:/transcode'
            - '${MEDIA_READ_DIR}/movies:/data/movies'
            - '${MEDIA_READ_DIR}/tvshows:/data/tvshows'
            - '${MEDIA_READ_DIR}/extras:/data/extras'
        labels:
            - 'traefik.frontend.rule=Host:plex.${DOMAIN}'
            - traefik.port=32400
    tautulli:
        image: 'linuxserver/tautulli:latest'
        container_name: tautulli
        restart: always
        environment:
            - 'PUID=${UID}'
            - 'PGID=${GID}'
            - TZ=Europe/London
        volumes:
            - '${CONFIG_DIR}/tautulli:/config'
            - '${CONFIG_DIR}/plex/Library/Application Support/Plex Media Server/Logs/:/logs'
        ports:
            - '8181:8181'
        labels:
            - 'traefik.frontend.rule=Host:tautulli.${DOMAIN}'
    traefik:
        image: 'traefik:latest'
        container_name: traefik
        restart: always
        networks:
            - default
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        expose:
            - 8080
        command: '--api --docker'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${CONFIG_DIR}/traefik/traefik.toml:/traefik.toml'
            - '${CONFIG_DIR}/traefik/acme.json:/acme.json'
        labels:
            - 'traefik.frontend.rule=Host:proxy.${DOMAIN}'
            - traefik.port=8080
    varken:
        image: 'boerderij/varken:latest'
        container_name: varken
        restart: always
        volumes:
            - '${CONFIG_DIR}/varken:/config'
        environment:
            - 'PGID=${GID}'
            - 'PUID=${UID}'
            - TZ=Europe/London
        depends_on:
            - influxdb
            - tautulli
