global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 5s
scrape_configs:
  - job_name: cadvisor
    scheme: http
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: node_exporter
    scheme: http
    static_configs:
      - targets:
        - node_exporter:9100

  - job_name: prometheus
    scheme: http
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: grafana
    scheme: http
    static_configs:
      - targets:
        - grafana:3000
