[accessLog]

[acme]
storage = "acme.json"
onHostRule = true
entryPoint = "https"
	
[acme.httpChallenge]
entryPoint = "http"

[api]
dashboard = true
insecure = true

[entrypoints.web]
address = ":80"

[metrics.influxDB]
address = "localhost:8086"

[providers.docker]
exposedByDefault = true
network = "jarvis"
watch = true

[tracing]
serviceName = "traefik"
spanNameLimit = 150
