name: 🚀 Deploy

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: .env
      run: cp example.env .env
    - name: Deploy
      run: docker-compose up -d
    - name: Check
      run: docker ps -a
    - name: Logs
      run: docker-compose logs
