name: Install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
        chmod +x ./install.sh
        ./install.sh
    - name: Deploy
      run: docker-compose up -d
