name: Install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      run: docker-compose up -d
    - name: Check
      run: docker ps -a
    - name: Logs
      run: docker-compose logs
